### ISSUE TITLE
Sudo error

### ISSUE THREAD

**Issue by mishailovic** [botgram/shell-bot#20]
I installed the bot on my Raspberry Pi and it works great.  But I have problems with some commands, like pip and apt.  
Here's what I get: 
![IMG_20200123_230754](https://user-images.githubusercontent.com/41520056/73020016-d1aa2900-3e35-11ea-84e8-6eccc87bb05d.jpg)
Yeah, and server running from sudo, i don't know where is problem

How can I fix this?

**Comment by avissian** [comment]
What does the `/run echo $USER` command output? Is username correct?

**Comment by mishailovic** [comment]
@avissian  Yes, it says I'm root

**Comment by mildsunrise** [comment]
WTF, I can't figure out why that would happen

what's the output of `/run id`?

**Comment by mildsunrise** [comment]
also, how are you running the server? manually from a terminal?

**Comment by mishailovic** [comment]
Yep, manually

**Comment by hurondefuego** [comment]
I will write here because the title of the issue:

@mildsunrise I have a problem with `sudo`   as well, but when I use it, the process doesn't continue, it stay like frozen. It doesn't matter if I use `sudo [command]` or when I use `sudo -s` I have to use `/kill` because it doesn't work.

**I don't know how to insert an screenshot from phone, so I leave the link here:** 
https://thumb.cloud.mail.ru/weblink/thumb/xw0/2cjq/joAGPgCJF/Screenshot_20200222-224612_Telegram-01.jpeg

The system I'm using is: Xubuntu 18
Thank you. The program is work good (except for sudo)

**Comment by mildsunrise** [comment]
@hurondefuego try to enable [passwordless sudo](https://askubuntu.com/questions/192050/how-to-run-sudo-command-with-no-password) for a moment, and try again. If it works this way, then it's surely due to the password prompt

**Comment by mishailovic** [comment]
Hmm, I don’t even know what the problem was.  I reinstalled the OS on my raspberry pi, and now everything works perfectly.
